version: "3.8"

services:
    api:
        build: ./app
        ports: 
            - 8000:8000
        environment:
            - DB_URL=mongodb://db/library_db
        volumes:
            - ./app:/app
    db:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - taskdb:/data/db
volumes:
    taskdb: